name: Auto Release Tool by Intuit
author: mbround18
description: Run Auto by Intuit on your repo
branding:
  icon: arrow-up
  color: purple
inputs:
  jqVersion:
    description: "Version if jq to use"
    required: true
    default: "1.6"
  autoVersion:
    description: "Version of auto to install"
    required: true
    default: "latest"
  token:
    description: "Admin Pat to use"
    required: true
  command:
    description: "Auto command to run"
    required: true
    default: "shipit -v"
outputs:
  version:
    description: "Outputs the auto version."
    value: ${{ steps.auto.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Setup Bins
      shell: bash
      run: |
        export BIN_PATH="${GITHUB_ACTION_PATH}/.bin"
        mkdir -p "${BIN_PATH}"
        echo "${BIN_PATH}" >> $GITHUB_PATH

    - name: Setup JQ
      shell: bash
      if: inputs.autoVersion == 'latest'
      run: |
        echo "Setting jq path..."
        export JQ_PATH="${GITHUB_ACTION_PATH}/.bin/jq"
        echo "JQ_PATH=${JQ_PATH}"
        echo "Downloading jq..."
        wget -O "${JQ_PATH}" "https://github.com/stedolan/jq/releases/download/jq-${{inputs.jqVersion}}/jq-linux64"
        echo "Making jq exectuabe..."
        chmod +x "${JQ_PATH}"
        echo "jq setup complete..."

    - name: Setup Auto
      shell: bash
      run: |
        echo "Setting auto path..."
        export AUTO_PATH="${GITHUB_ACTION_PATH}/.bin/auto"
        echo "AUTO_PATH=${AUTO_PATH}"

        export AUTO_URL=""
        echo "Downloading auto..."
        if [ "${{ inputs.autoVersion }}" = "latest" ]; then
          echo "Fetching latest auto release..."
          export LATEST_TAG="$(curl https://api.github.com/repos/intuit/auto/releases/latest -s | jq .name -r | xargs)"
          AUTO_URL="https://github.com/intuit/auto/releases/download/${LATEST_TAG}/auto-linux.gz"
        else
          AUTO_URL="https://github.com/intuit/auto/releases/download/${{ inputs.autoVersion }}/auto-linux.gz"
        fi
        curl -vkL -o - "${AUTO_URL}" | gunzip > "${AUTO_PATH}"
        echo "Making auto executable..."
        chmod +x "${AUTO_PATH}"
        echo "auto setup complete..."

    - name: Setup Bins
      id: auto
      shell: bash
      env:
        GH_TOKEN: "${{ inputs.token }}"
      run: |
        cleanup() {
          EXIT_STATUS=$?  # Eg 130 for SIGINT, 128 + (2 == SIGINT)
          LAST_LINE="$(tail -1 /tmp/auto.out)"
          
          if [ ! "$EXIT_STATUS" -eq 0 ]; then 
            exit ${EXIT_STATUS}  
          fi 
        
          VERSION=""
        
          case "${LAST_LINE}" in
            *releases/tag*)
              VERSION="$(echo "${LAST_LINE}" | cut -d "/" -f8 | xargs)"
            ;;
            *canary*)
              VERSION=$(echo "${LAST_LINE}" | cut -d ":" -f2 | xargs)
            ;;
            *)
              VERSION=
            ;;
          esac
        
          echo "Exit Code=${EXIT_STATUS}"
          echo "Version=${VERSION}"
          echo "::set-output name=version::${VERSION}"
          
          exit ${EXIT_STATUS}
        }

        # Setting up script traps
        trap 'cleanup' EXIT INT TERM

        # Launch Auto
        auto ${{ inputs.command }} 2>&1 | tee /tmp/auto.out

