name: Auto
author: mbround18
description: Run Auto by Intuit on your repo
inputs:
  jqVersion: 
    description: 'Version if jq to use'
    required: true
    default: '1.6'
    type: string
  command:
    description: 'Auto command to run'
    required: true
    default: 'shipit -v'
    type: string
    
runs:
  using: "composite"
  steps:
    - name: Setup Bins
      shell: bash
      run: |
        export BIN_PATH="$GITHUB_ACTION_PATH/.bin"
        mkdir -p "${BIN_PATH}"
        echo "${BIN_PATH}" >> $GITHUB_PATH
    
    - name: Setup JQ
      shell: bash
      run: |
        echo "Setting jq path..."
        export jQ_PATH="$GITHUB_ACTION_PATH/.bin/jq"
        
        echo "Downloading jq..."
        wget -O "${JQ_PATH}" "https://github.com/stedolan/jq/releases/download/jq-${{inputs.jqVersion}}/jq-linux64"
        
        echo "Making jq exectuabe..."
        chmod +x "${JQ_PATH}"
        
        echo "jq setup complete..."
        
    - name: Setup Auto
      shell: bash
      run: |
        echo "Setting auto path..."
        export AUTO_PATH="$GITHUB_ACTION_PATH/.bin/auto"
        
        echo "Fetching latest auto release..."
        export LATEST_TAG="$(curl https://api.github.com/repos/intuit/auto/releases/latest -s | jq .name -r | xargs)"
        
        echo "Downloading auto..."
        curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > "${AUTO_PATH}"
        
        echo "Making auto executable..."
        chmod +x "${AUTO_PATH}"
     
        echo "auto setup complete..."
    
    - name: Setup Bins
      shell: bash
      run: |
        auto "${{ inputs.command }}"
