name: Release

on: [push]

env: 
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clonse
        uses: actions/checkout@v3
      
      - name: Release
        uses: ./
